<?php

use Illuminate\Database\Seeder;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $members = array(
          array(
            'nama' => 'Shkodran Mustafi',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '20',
            'foto' => 'images/player/1/Shkodran_Mustafi.jpg',
            'participant_id' => '1',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Mesut Ozil',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '11',
            'foto' => 'images/player/1/Mesut_Ozil.jpg',
            'participant_id' => '1',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Granit Xhaka',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '29',
            'foto' => 'images/player/1/Granit_Xhaka.jpg',
            'participant_id' => '1',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Alexis Sanchez',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '7',
            'foto' => 'images/player/2/Alexis_Sanchez.jpg',
            'participant_id' => '2',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Lucas Perez',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '9',
            'foto' => 'images/player/2/Lucas_Perez.jpg',
            'participant_id' => '2',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Olivier Giroud',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '12',
            'foto' => 'images/player/2/Olivier_Giroud.jpg',
            'participant_id' => '2',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Aaron Ramsey',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '8',
            'foto' => 'images/player/3/Aaron_Ramsey.jpg',
            'participant_id' => '3',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Rob Holding',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '16',
            'foto' => 'images/player/3/Rob_Holding.jpg',
            'participant_id' => '3',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Gabriel Paulista',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '5',
            'foto' => 'images/player/3/Gabriel_Paulista.jpg',
            'participant_id' => '3',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Theo Walcott',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '14',
            'foto' => 'images/player/4/Theo_Walcott.jpg',
            'participant_id' => '4',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Petr Cech',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penjaga Gawang',
            'no_punggung' => '33',
            'foto' => 'images/player/4/Petr_Cech.jpg',
            'participant_id' => '4',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Mohamed Elneny',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '35',
            'foto' => 'images/player/4/Mohamed_Elneny.jpg',
            'participant_id' => '4',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Laurent Koscielny',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '6',
            'foto' => 'images/player/5/Laurent_Koscielny.jpg',
            'participant_id' => '5',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Hector Bellerin',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '24',
            'foto' => 'images/player/5/Hector_Bellerin.jpg',
            'participant_id' => '5',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Santi Cazorla',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '19',
            'foto' => 'images/player/5/Santi_Cazorla.jpg',
            'participant_id' => '5',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Alex Oxlade-Chamberlain',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '15',
            'foto' => 'images/player/6/Alex_Oxlade_Chamberlain.jpg',
            'participant_id' => '6',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Alex Iwobi',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '17',
            'foto' => 'images/player/6/Alex_Iwobi.jpg',
            'participant_id' => '6',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Danny Welbeck',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '23',
            'foto' => 'images/player/6/Danny_Welbeck.jpg',
            'participant_id' => '6',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Yaya Sanogo',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '22',
            'foto' => 'images/player/7/Yaya_Sanogo.jpg',
            'participant_id' => '7',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Mathieu Debuchy',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '2',
            'foto' => 'images/player/7/Mathieu_Debuchy.jpg',
            'participant_id' => '7',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'David Ospina',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penjaga Gawang',
            'no_punggung' => '13',
            'foto' => 'images/player/7/David_Ospina.jpg',
            'participant_id' => '7',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Chuba Akpom',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Penyerang',
            'no_punggung' => '32',
            'foto' => 'images/player/8/Chuba_Akpom.jpg',
            'participant_id' => '8',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Per Mertesacker',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Bek',
            'no_punggung' => '4',
            'foto' => 'images/player/8/Per_Mertesacker.jpg',
            'participant_id' => '8',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          ),array(
            'nama' => 'Krystian Bielik',
            'jk' => 'L',
            'tgl_lhr' => '2016-09-06',
            'no_hp' => '082167453377',
            'posisi' => 'Gelandang',
            'no_punggung' => '37',
            'foto' => 'images/player/8/Krystian_Bielik.jpg',
            'participant_id' => '8',
            'created_at' => DB::raw('NOW()'),
            'updated_at' => DB::raw('NOW()'),
          )
        );
        // Comment the below to stop the seeder
        DB::table('members')->insert($members);
    }
}
